/// Flutter icons NotesCustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotesCustomIcons
///      fonts:
///       - asset: fonts/NotesCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NotesCustomIcons {
  NotesCustomIcons._();

  static const _kFontFam = 'NotesCustomIcons';

  static const IconData ic_check_box_grey900_alpha71_24 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_grid_view_grey700_24 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_image_grey900_alpha71_24 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_list_view_grey700_24 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_brush_grey900_alpha71_24 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_add_alert_grey900_alpha71_24 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_add_box_grey900_alpha71_24 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData ic_archive_grey900_alpha71_24 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData ic_keep_pin_outline_grey900_alpha71_24 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ic_place_grey900_alpha71_18 = const IconData(0xe809, fontFamily: _kFontFam);
}
